[CCTransactionApp]
appHost = "localhost"
appPort = 9096

[CCTransactionApp.dbConnector]
username = "<USER_NAME>"
password = "<PASSWORD>"

[CCTransactionApp.dbConnector.database]
port = 3306
name = "CREDIT_CARD"
